name: gif_flutter_libs
description: A package to flutter libs
#publish_to: https://pub.dartlang.org
version: 0.0.4
issue_tracker: https://github.com/gif-gif/flutter.io/issues
homepage: https://github.com/gif-gif/flutter.io/flutter_libs

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.6.1
  dio: ^5.2.1+1
  date_format: ^2.0.7
  encrypt: ^5.0.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  built_value_generator: ^8.6.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
